### PR TITLE
feat: import from autoware_common

### PR DESCRIPTION
**Pull request by youtalk**
This PR has Imported `autoware_cmake` and `autoware_lint_common` packages from https://github.com/autowarefoundation/autoware_common

ref. https://github.com/orgs/autowarefoundation/discussions/4671

### CODE REVIEW

**Review by esteve — COMMENTED** [review]
Like with https://github.com/autowarefoundation/autoware_utils/pull/1#issuecomment-2088102795, what do you think of using `git subtree split` to preserve the history of the autoware_common history?

**Comment by youtalk** [comment]
@esteve I've used `git subtree split` to preserve the history. Please review again.

**Review by esteve — APPROVED** [review]
@youtalk LGTM, thanks for addressing my feedback 🙂

**Comment by youtalk** [comment]
To preserve the commit history, I've used merge commit for this PR.

**Pull request merged**
